language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - gem update --system
  - gem --version

before_script:
  - RAILS_ENV=test bundle exec rake meishi:setup_test
  - RAILS_ENV=test bundle exec rake db:migrate

script: NO_COV=true bundle exec rspec --format=documentation
